baseURL = "https://nycu-haix.github.io/"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "Human-AI & Creative Computing (HAIX) Lab"
theme = "anubis2"
enableRobotsTXT = true
disableKinds = ["taxonomy", "term"]

[permalinks]
people = "/people/:slug/"

[params]
description = "Human-AI & Creative Computing (HAIX) Lab at National Yang Ming Chiao Tung University"

[params.author]
name = "Human-AI & Creative Computing (HAIX) Lab"
location = "Hsinchu, Taiwan"

[params.anubis2]
colortheme = "light"
enablecolorthemeswitcher = false
hidefooterattribution = true

[params.anubis2.services]

[params.anubis2.services.googleanalytics]
gtag = "G-JM618SFJRK"

[markup.goldmark.extensions.typographer]
apostrophe = "&#39;"
leftSingleQuote = "&#39;"
rightSingleQuote = "&#39;"

[markup.goldmark.renderer]
unsafe = true
