baseURL = "https://nycu-haix.github.io/"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "NYCU HAIX Lab"
theme = "anubis2"

[params]
description = "HAIX Lab at National Yang Ming Chiao Tung University"

[params.author]
name = "HAIX Lab"
location = "Hsinchu, Taiwan"

[params.anubis2]
colortheme = "light"
enablecolorthemeswitcher = false
hidefooterattribution = true

[params.anubis2.services]

[markup.goldmark.renderer]
unsafe = true
