baseURL = "https://nycu-haix.github.io/"
languageCode = "en-us"
defaultContentLanguage = "en"
title = "HAIX (Human AI & Creative Computing) Lab"
theme = "anubis2"
enableRobotsTXT = true
disableKinds = ["taxonomy", "term"]

[permalinks]
members = "/:slug/"

[params]
description = "HAIX (Human AI & Creative Computing) Lab at National Yang Ming Chiao Tung University"

[params.author]
name = "HAIX (Human AI & Creative Computing) Lab"
location = "Hsinchu, Taiwan"

[params.anubis2]
colortheme = "light"
enablecolorthemeswitcher = false
hidefooterattribution = true

[params.anubis2.services]

[params.anubis2.services.googleanalytics]
gtag = "G-JM618SFJRK"

[markup.goldmark.renderer]
unsafe = true
